### ISSUE TITLE
How can one access the selected month and year and say print the result?

### ISSUE THREAD

**Issue by sookwalinga** [sivaprasadnk/SimpleMonthYearPicker#2]

**Comment by sookwalinga** [comment]
I have created a pr to show how to access this information: https://github.com/sivaprasadnk/SimpleMonthYearPicker/pull/4
#4

**Comment by sookwalinga** [comment]
I also added another optional prop, disableFuture, to allow the user to disable years higher than the current year

**Comment by sivaprasadnk** [comment]
@sookwalinga updated package (1.0.4), without noticing your disableFuture changes, can you make changes and give a pull request again?

**Comment by sookwalinga** [comment]
Alright @sivaprasadnk I will put in another pr, thanks.

**Comment by sookwalinga** [comment]
I have put in another pr @sivaprasadnk

**Comment by sivaprasadnk** [comment]
@sookwalinga pr merged, thanks !
